const list = [
    {
      id: 1,
      title: "Amazon Brand - Inkast Denim Co. Men's Slim Casual Shirt",
      author: "Sold by Cocoblu Retail and Fulfilled by Amazon.",
      price: 589,
      img:"https://m.media-amazon.com/images/I/81kJzDOwjNL._UX466_.jpg",
      amount: 1,
    },
    {
      id: 2,
      title: "Unisex-Adult Cotton Hooded Neck Avenger Printed Hoodie",
      author: "Sold by More & More Tshirts and Fulfilled by Amazon.",
      price: 999,
      img: "https://m.media-amazon.com/images/I/71yCPm-BJgL._UY606_.jpg",
      amount: 1,
    },
    {
      id: 3,
      title: "Amazon Brand - Symbol Men's Regular Casual Trousers",
      author: "Sold By Amazon",
      price: 299,
      img: "https://m.media-amazon.com/images/I/71MW2+0BFQL._UX569_.jpg",
      amount: 1,
    },
    {
      id: 4,
      title: "Prakasam Cotton Mens White Cotton Dhoti with Jari Border",
      author: "Visit the PRAKASAM COTTON Store",
      price: 357,
      img: "https://m.media-amazon.com/images/I/61utSJRcj-L._UY606_.jpg",
      amount: 1,
    },
    {
      id: 5,
      title: "Romano nx Men's 100% Cotton Cargo Shorts Bermuda with Multi-Pockets & Side Zipper Pockets in 5 Colors",
      author: "Visit the Romano Store",
      price: 149,
      img: "https://m.media-amazon.com/images/I/41RIJBMFEDL._UY679_.jpg",
      amount: 1,
    },
    {
      id: 6,
      title: "TABARD KURTA CHURIDAR SET FOR MENS",
      author: "Visit the TABARD Store",
      price: 135,
      img: "https://m.media-amazon.com/images/I/81SGv6NwJRL._UY606_.jpg",
      amount: 1,
    },
    {
      id: 7,
      title: "The Souled Store Men Official CSK: Finish Like Dhoni Navy Blue Printed T-Shirts",
      author: "Visit the The Souled Store Store",
      price: 693,
      img: "https://m.media-amazon.com/images/I/517PNVuUJpL._UY606_.jpg",
      amount: 1,
    },
    {
      id: 8,
      title: "ALAMOS Combo Pack of 2 edixo Cap",
      author: "Brand:ALAMOS",
      price: 289,
      img: "https://m.media-amazon.com/images/I/71mcY2boNVL._UX679_.jpg",
      amount: 1,
    },
    {
      id: 9,
      title: "Besimple Men's Bomber Full Sleeve Jacket",
      author: "Visit the BESIMPLE Store",
      price: 1080,
      img: "https://m.media-amazon.com/images/I/61BG74XJd3L._UX679_.jpg",
      amount: 1,
    },
    {
      id: 10,
      title: "Dhingra Men's Regular Fit Bandhgala Jodhpuri Style Blazer",
      author: "Brand: Dhingra",
      price:5086,
      img: "https://m.media-amazon.com/images/I/5147Msr1aXL._UX679_.jpg",
      amount: 1,
    },
    {
      id: 11,
      title: "blackberrys Men's Slim Fit Suit",
      author: "Visit the blackberrys Store",
      price: 11020,
      img: "https://m.media-amazon.com/images/I/51iDDXoQklL._UX679_.jpg",
      amount: 1,
    },
    {
      id: 12,
      title: "ELEGANTE Men's Square Sunglasses",
      author: "Visit the ELEGANTE Store",
      price: 157,
      img: "https://m.media-amazon.com/images/I/515gKnUgwpL._UX679_.jpg",
      amount: 1,
    },
  ];
  
  export default list;